# Generated by Django 5.2.1 on 2025-05-14 09:39

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Call',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phonet_uuid', models.CharField(max_length=100, unique=True)),
                ('parent_uuid', models.CharField(blank=True, max_length=100, null=True)),
                ('direction', models.PositiveSmallIntegerField(help_text='1=internal, 2=outgoing, 4=incoming, etc.', verbose_name='Напрямок дзвінка')),
                ('leg_id', models.CharField(blank=True, max_length=100, null=True)),
                ('leg_ext', models.CharField(blank=True, max_length=50, null=True)),
                ('leg_name', models.CharField(blank=True, max_length=100, null=True)),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('answer_time', models.DateTimeField(blank=True, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('description', models.TextField(blank=True)),
                ('recording_link', models.URLField(blank=True, null=True)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calls', to='contacts.contact')),
                ('contact_phone', models.ForeignKey(blank=True, max_length=20, null=True, on_delete=django.db.models.deletion.CASCADE, to='contacts.contactphone')),
            ],
        ),
    ]
