# Generated by Django 5.2.1 on 2025-05-14 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactemail',
            name='name',
            field=models.CharField(default='Основний', max_length=50, verbose_name='Назва'),
        ),
        migrations.AddField(
            model_name='contactphone',
            name='name',
            field=models.CharField(default='Основний', max_length=50, verbose_name='Назва'),
        ),
    ]
