# Generated by Django 5.2.1 on 2025-05-14 12:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
        ('contacts', '0002_contactemail_name_contactphone_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='companies.company', verbose_name='Компанія'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='last_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Прізвище'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='position',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Посада'),
        ),
        migrations.AlterField(
            model_name='contactphone',
            name='telegram_username',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Telegram Username'),
        ),
    ]
