# Generated by Django 5.2.1 on 2025-05-12 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='status',
            field=models.CharField(choices=[('working', 'Working'), ('fired', 'Fired'), ('on_vacation', 'On Vacation')], default='working', max_length=20, verbose_name='Status'),
        ),
    ]
