# Generated by Django 5.2.1 on 2025-05-15 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_customuser_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='phonet_extension',
            field=models.CharField(blank=True, help_text='Internal Phonet extension number (e.g., 001)', max_length=50, null=True, unique=True, verbose_name='Phonet Extension'),
        ),
    ]
