# Generated by Django 5.2.1 on 2025-05-12 23:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Назва')),
                ('work_id', models.CharField(blank=True, max_length=50, null=True, verbose_name='Work ID')),
                ('rabota_id', models.CharField(blank=True, max_length=50, null=True, verbose_name='Rabota ID')),
                ('just_id', models.CharField(blank=True, max_length=50, null=True, verbose_name='Just ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата створення')),
                ('slug', models.SlugField(allow_unicode=True, max_length=255, unique=True, verbose_name='Слаг')),
                ('responsible', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Відповідальний')),
            ],
            options={
                'verbose_name': 'Компанія',
                'verbose_name_plural': 'Компанії',
            },
        ),
    ]
