"""
Django settings for just_crm project.

Generated by 'django-admin startproject' using Django 5.2.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-(o1gbl)c@6vd(%8-t=fveibv!om+fiy6^rf=zkbe^#y2qroipb'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['185.233.117.107', 'localhost', 'just-crm.online', 'www.just-crm.online',]


# Application definition

INSTALLED_APPS = [
    'daphne',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'main',
    'contacts',
    'companies',
    'chats',
    'calls',
    'emails',
    'sales',
    'tasks',
    'sales_viber.apps.SalesViberConfig',
    'sales_telegram.apps.SalesTelegramConfig',
    'vacancies',
    'parser',

    'channels',
    'rest_framework',


]



AUTH_USER_MODEL = 'main.CustomUser'


MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',

]

ROOT_URLCONF = 'just_crm.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

# Налаштування для логіну та логауту
LOGIN_REDIRECT_URL = 'home'  # Перенаправлення після логіну на головну сторінку
LOGOUT_REDIRECT_URL = 'login'  # Перенаправлення після логауту на сторінку логіну
LOGIN_URL = 'login'  # URL для перенаправлення неавторизованих користувачів

WSGI_APPLICATION = 'just_crm.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

#DATABASES = {
#    'default': {
#        'ENGINE': 'django.db.backends.sqlite3',
#        'NAME': BASE_DIR / 'db.sqlite3',
#    }
#}


DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'jrm_new',
        'USER': 'jrm_new',
        'PASSWORD': '89P62SFpta',
        'HOST': 'prdsv558.mysql.network',
        'PORT': '10544',
        'OPTIONS': {
            'init_command': "SET sql_mode='STRICT_TRANS_TABLES'",
        },
    }
}

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

# Налаштування для статичних файлів
STATIC_URL = '/static/'
STATIC_ROOT = '/var/www/static'

# Налаштування для медіа-файлів
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Налаштування сесій
SESSION_COOKIE_AGE = 900  # 15 хвилин у секундах
SESSION_EXPIRE_AT_BROWSER_CLOSE = True  # Сесія закінчується при закритті браузера
SESSION_SAVE_EVERY_REQUEST = True  # Оновлювати сесію при кожному запиті

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


PHONET_IP_WHITELIST = [
    '89.184.65.208',
    '89.184.82.130',
    '89.184.67.228',
    '89.184.82.191',
    '89.184.65.137',
    '95.213.132.131',
    '*',
]

PHONET_API_URL = 'https://contactlogistic.phonet.com.ua'  # Замініть на ваш домен Phonet
PHONET_API_KEY = 'ZvQFVmZF6a0EthybFi8HsS5bH7mzU0eJ'  # Отримайте в кабінеті Phonet

ASGI_APPLICATION = 'just_crm.asgi.application'

CHANNEL_LAYERS = {
    'default': {
        'BACKEND': 'channels_redis.core.RedisChannelLayer',
        'CONFIG': {
            'hosts': [('127.0.0.1', 6379)],
        },
    },
}

MATRIX_SERVER = 'https://matrix.just-crm.online'
MATRIX_ADMIN_USERNAME = '@myadmin:matrix.just-crm.online'
MATRIX_ADMIN_PASSWORD = 'S3cret!'
MATRIX_TELEGRAM_BOT = '@telegrambot:matrix.just-crm.online'


import os
import logging
import logging.config

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,

    # -----------------------------------------------------------------
    # 1. Хендлери
    # -----------------------------------------------------------------
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
            "level": "DEBUG",          # <-- мінімальний рівень у консоль
            "formatter": "verbose",
        },
    },

    # -----------------------------------------------------------------
    # 2. Форматери
    # -----------------------------------------------------------------
    "formatters": {
        "verbose": {
            "format": "[{asctime}] {levelname:<7} {name}: {message}",
            "style": "{",
            "datefmt": "%H:%M:%S",
        },
    },

    # -----------------------------------------------------------------
    # 3. Логери
    # -----------------------------------------------------------------
    "loggers": {
        # увесь ваш проєкт (за бажанням можна понизити до INFO)
        "": {
            "handlers": ["console"],
            "level": "INFO",
        },
        # --- CHANGE: вмикаємо DEBUG саме для нашого пакета ------------
        "sales_telegram": {
            "handlers": ["console"],
            "level": "DEBUG",
            "propagate": False,        # щоб не дублювалося у ""-логер
        },
        "sales_viber.api": {      # увесь діалог із E-chat
                "handlers": ["console"],
                "level": "DEBUG",
                "propagate": False,
        },
    },
}


CELERY_BROKER_URL = 'redis://127.0.0.1:6379/0'
CELERY_RESULT_BACKEND = 'redis://127.0.0.1:6379/0'
CELERY_TIMEZONE = TIME_ZONE          # вже є UTC